{"kind":"article","metadata":{"title":"Equatable Implementations","modules":[{"name":"FoundationExtras"}],"role":"collectionGroup","roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/Equatable-Implementations"},"sections":[],"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/!=(_:_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/foundationextras\/tryfrom\/failure\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/FoundationExtras\/documentation\/FoundationExtras","doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom","doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure"]]},"references":{"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure":{"role":"symbol","title":"TryFrom.Failure","abstract":[{"text":"A universal error type that is available to all custom implementations of the TryFrom trait.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"}],"type":"topic","url":"\/documentation\/foundationextras\/tryfrom\/failure","kind":"symbol","navigatorTitle":[{"text":"Failure","kind":"identifier"}],"identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure"},"doc://FoundationExtras/documentation/FoundationExtras":{"role":"collection","title":"FoundationExtras","abstract":[{"type":"text","text":"Useful extensions to the Foundation framework."}],"type":"topic","url":"\/documentation\/foundationextras","kind":"symbol","identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras"},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom/Failure/!=(_:_:)":{"kind":"symbol","type":"topic","abstract":[],"title":"!=(_:_:)","role":"symbol","identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom\/Failure\/!=(_:_:)","url":"\/documentation\/foundationextras\/tryfrom\/failure\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://FoundationExtras/documentation/FoundationExtras/TryFrom":{"role":"symbol","title":"TryFrom","abstract":[{"text":"Protocols in Swift are limited, period. Protocols cannot be implemented multiple times with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"different implementations!"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TryFrom","kind":"identifier"}],"type":"topic","url":"\/documentation\/foundationextras\/tryfrom","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TryFrom"}],"identifier":"doc:\/\/FoundationExtras\/documentation\/FoundationExtras\/TryFrom"}}}